development:
   oauth:
      application:
         name: Oee
         uid: bdae4504bd3fc97d0690b6b57a7cc5b7399a5c91c3a126731c0da4b26f606991
         redirect_uri: 'http://localhost:9000'
         owner: admin@oee.com
      secret_key: 7381a978f7dd7f9a1117
   application:
       id: oee-client




production:
   oauth:
      application:
         name: Oee
         uid: bdae4504bd3fc97d0690b6b57a7cc5b7399a5c91c3a126731c0da4b26f606991
         redirect_uri: 'https://localhost:9000'
         owner: admin@oee.com
      secret_key: 7381a978f7dd7f9a1117
   application:
       id: oee-client
